name: "Open PR"

on:
  workflow_call:
  
jobs:

  open-pr:
    name: open-pr
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.open-pr.outputs.pr_number }}
    steps:

      - uses: actions/checkout@v3

      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "AUTOMATIC PR: FEATURE -> MAIN"
          # pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          # pr_reviewer: "paigen11"
          pr_draft: false






