defaults:
  run:
    working-directory: .
permissions:
  pull-requests: write

name: "Deploy Infrastructure"

on:
  push:
    branches:
      - main

env:
 # verbosity setting for Terraform logs
 TF_LOG: ${{ vars.TF_LOG}}
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_REGION: ${{ vars.AWS_REGION }}
 # S3 bucket for the Terraform state
 BUCKET_TF_STATE: ${{ vars.BUCKET_TF_STATE}}
 BUCKET_TF_KEY: ${{ vars.BUCKET_TF_KEY}}
 TF_DESTROY: ${{ vars.TF_DESTROY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "~> 1.6"

      - name: Create backend file
        run: |
          cat << 'EOF' > ${{ github.workspace }}/backend.tfvars
            bucket =  "${{ env.BUCKET_TF_STATE }}"
            key    =  "/test/${{ env.BUCKET_TF_STATE }}"
            region =  "${{ env.AWS_REGION }}" 
          EOF
        shell: bash


      - name: Terraform fmt
        id: fmt
        run: terraform fmt 
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: terraform init  -backend-config="${{ github.workspace }}/backend.tfvars"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
     



